#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Maia's Portfolio

  Hi! My name is Maia Lemos and I'm a sophmore studying Computer Science and
  Media Arts at Northeastern University's Khoury College.


  I have taken a couple programming classes in highschool, however I have started
  coding in earnest starting my first year of college. I have been working on learning
  a variety of languages, Java in particular, through my courses. However, I also
  have experience in HTML, CSS, Ruby, and JavaScript. I have also experimented
  by creating my own personal projects to further my learning in
  object-oriented concepts and web development.


  This website is a portfolio of my art and computer science projects. You will
  find these in the Project tab. The Blog tab will be composed of posts similar
  to annoucements from my academic life. Lastly, if you wish to contact me
  through email, please visit the Contact tab.


  Thank you for visiting my page!


  Credit:
  This is the portfolio site for Maia Lemos, built on Jekyll and hosted on Github.
  Based on a theme by Le Paul, available on [his GitHub repository](https://github.com/LeNPaul/portfolio-jekyll-theme/fork).

#  This is a personal portfolio theme that I built from the ground up, using the [DevTips Starter Kit](http://devtipsstarterkit.com/) as a foundation for starting, and following closely the amazing tutorial by [Travis Neilson over at DevTips](https://www.youtube.com/watch?v=T6jKLsxbFg4&list=PL0CB3OvPhDA_STygmp3sDenx3UpdOMk7P). You can [check out the demo](lenpaul.github.io/portfolio-jekyll-theme/), and [fork the repository](https://github.com/LeNPaul/portfolio-jekyll-theme/fork), to get started.

contact: >
  # Contact

  You may contact me [through my email](mailto:lemos.m-at-northeastern-dot-edu) or [through
  LinkedIn](https://www.linkedin.com/in/maia-lemos/) if you have any questions,
  wish to hire me, or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'Charcoal Series', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Image Processor', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Animations', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Maze Generator and Solver', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Art @ PEA', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/maialeelemos'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/maia-lemos/'}
- {icon: 'envelope', link: 'mailto:lemos.m-at-northeastern-dot-edu'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
